name: clean_flu_cli
description: Build a clean and organized Flutter app structure.
version: 0.1.0
repository: https://github.com/itisnajim/clean_flu_cli
issue_tracker: https://github.com/itisnajim/clean_flu_cli/issues
topics: [cli, codegen, template, boilerplate, architecture]

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  args: ^2.4.1
  cli_completion: ^0.3.0
  mason: ^0.1.0-dev.51
  mason_logger: ^0.2.5
  pub_updater: ^0.3.1
  universal_io: ^2.2.2

dev_dependencies:
  build_runner: ^2.4.4
  build_verify: ^3.1.0
  build_version: ^2.1.1
  mocktail: ^1.0.0
  test: ^1.24.6
  very_good_analysis: ^5.1.0

executables:
  clean_flu:
